name: seg_env
channels:
  - pytorch
  - defaults
dependencies:
  - matplotlib=3.3.4
  - numpy=1.19.1
  - opencv=3.3.1
  - pandas=1.1.1
  - python>=3.6
  - pytorch=1.7.0
  - scikit-learn=0.24.2
  - torchvision=0.8.1
